# Generated by Django 4.1.3 on 2022-11-16 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pictures.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height_field', models.PositiveIntegerField(blank=True, null=True)),
                ('width_field', models.PositiveIntegerField(blank=True, null=True)),
                ('picture', pictures.models.PictureField(aspect_ratios=[None, '1/1', '4/3'], breakpoints={'2xl': 1536, 'lg': 1024, 'md': 768, 'sm': 640, 'xl': 1280}, container_width=1200, file_types=['WEBP'], grid_columns=12, height_field='height_field', pixel_densities=[1, 2], upload_to='pictures', width_field='width_field')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='gallery.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
