# Generated by Django 4.1.3 on 2022-11-09 13:08

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_remove_post_foto_post_picture_alter_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="picture_height",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="picture_width",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                height_field=models.IntegerField(),
                pixel_densities=[1, 2],
                upload_to="user_uploads",
                width_field=models.IntegerField(),
            ),
        ),
    ]
