# Generated by Django 4.1.3 on 2022-11-09 13:10

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_post_picture_height_post_picture_width_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                height_field=models.CharField(max_length=200),
                pixel_densities=[1, 2],
                upload_to="user_uploads",
                width_field=models.CharField(max_length=200),
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="picture_height",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="picture_width",
            field=models.CharField(max_length=200),
        ),
    ]
