# Generated by Django 4.1.3 on 2022-11-09 13:26

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gallery",
            "0008_remove_post_picture_height_remove_post_picture_width_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="picture_height",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="picture_width",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=pictures.models.PictureField(
                aspect_ratios=[None, "1/1", "4/3"],
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                height_field="picture_height",
                pixel_densities=[1, 2],
                upload_to="pictures",
                width_field="picture_width",
            ),
        ),
    ]
