# Generated by Django 4.1.3 on 2022-11-09 13:50

from django.db import migrations
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gallery",
            "0010_remove_post_picture_height_remove_post_picture_width_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=pictures.models.PictureField(
                aspect_ratios=[None, "1/1"],
                breakpoints={"2xl": 1536, "lg": 1024, "md": 768, "sm": 640, "xl": 1280},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                pixel_densities=[1, 2],
                upload_to="pictures",
            ),
        ),
    ]
