# Generated by Django 4.1.3 on 2022-11-09 14:55

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0011_alter_post_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="height_field",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="width_field",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=pictures.models.PictureField(
                aspect_ratios=[None, "1/1"],
                breakpoints={"2xl": 1536, "lg": 1024, "md": 768, "sm": 640, "xl": 1280},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                height_field="height_field",
                pixel_densities=[1, 2],
                upload_to="pictures",
                width_field="width_field",
            ),
        ),
    ]
