# Generated by Django 4.1.3 on 2022-11-11 09:45

from django.db import migrations
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0012_post_height_field_post_width_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=pictures.models.PictureField(
                aspect_ratios=[None, "1/1", "4/3"],
                breakpoints={"2xl": 1536, "lg": 1024, "md": 768, "sm": 640, "xl": 1280},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                height_field="height_field",
                pixel_densities=[1, 2],
                upload_to="pictures",
                width_field="width_field",
            ),
        ),
    ]
